name = "java"
title = "Java Sync"
intersphinx = ["https://mongodb.com/docs/manual/objects.inv",
               "https://mongodb.com/docs/drivers/objects.inv"]

toc_landing_pages = [
    "/fundamentals/connection",
    "/fundamentals/crud",
    "/fundamentals/builders",
    "/usage-examples"
]
sharedinclude_root = "https://raw.githubusercontent.com/10gen/docs-shared/main/"

[constants]
version = "4.4"
full-version = "{+version+}.2"
mdb-server = "MongoDB Server"

package-name-org = "mongodb-org"
api = "https://mongodb.github.io/mongo-java-driver/{+version+}"
stable-api = "Stable API"
